# Dependencies
plugins: [jekyll-paginate]
excerpt_separator: <!--expand-->
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Detective Stat
tagline:          Scientific log
description:      Physicist interested in statistical science
url:              https://erg0dic.github.io/
baseurl:          /

author:
  name:           Irtaza Khalid
  email:          mdirtazausmankhalid@gmail.com'

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/erg0dic

social:
    linkedin: https://www.linkedin.com/in/ir1aza/

more_links:
    notes: 

